services:

  api:
    container_name: api-container
    image: android-api
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5100:8080
    volumes:
      - ./volumes/api/images:/app/Data/Images
    depends_on:
      - postgresql

  postgresql:
    container_name: postgresql-db-container
    image: postgres:latest
    restart: on-failure
    ports:
      - 5400:5432
    environment:
      POSTGRES_PASSWORD: devDb1234
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  redis:
    container_name: redis-cache-container
    image: redis:latest
    restart: on-failure
    ports:
      - 6300:6379
    volumes:
      - ./volumes/redis/data:/data